# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ccli.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ccli.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import basicTypes_pb2 as basicTypes__pb2
import template_pb2 as template__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nccli.proto\x12\x07rv.data\x1a\x10\x62\x61sicTypes.proto\x1a\x0etemplate.proto\"\xe8\x02\n\x0c\x43\x43LIDocument\x12\x32\n\x10\x61pplication_info\x18\x01 \x01(\x0b\x32\x18.rv.data.ApplicationInfo\x12\x1b\n\x13\x65nable_ccli_display\x18\x02 \x01(\x08\x12\x14\n\x0c\x63\x63li_license\x18\x03 \x01(\t\x12\x37\n\x0c\x64isplay_type\x18\x04 \x01(\x0e\x32!.rv.data.CCLIDocument.DisplayType\x12)\n\x08template\x18\x05 \x01(\x0b\x32\x17.rv.data.Template.Slide\"\x8c\x01\n\x0b\x44isplayType\x12\x1c\n\x18\x44ISPLAY_TYPE_FIRST_SLIDE\x10\x00\x12\x1b\n\x17\x44ISPLAY_TYPE_LAST_SLIDE\x10\x01\x12%\n!DISPLAY_TYPE_FIRST_AND_LAST_SLIDE\x10\x02\x12\x1b\n\x17\x44ISPLAY_TYPE_ALL_SLIDES\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ccli_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CCLIDOCUMENT']._serialized_start=58
  _globals['_CCLIDOCUMENT']._serialized_end=418
  _globals['_CCLIDOCUMENT_DISPLAYTYPE']._serialized_start=278
  _globals['_CCLIDOCUMENT_DISPLAYTYPE']._serialized_end=418
# @@protoc_insertion_point(module_scope)
