# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: groups.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'groups.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import basicTypes_pb2 as basicTypes__pb2
import hotKey_pb2 as hotKey__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cgroups.proto\x12\x07rv.data\x1a\x10\x62\x61sicTypes.proto\x1a\x0chotKey.proto\"\xc7\x01\n\x05Group\x12\x1b\n\x04uuid\x18\x01 \x01(\x0b\x32\r.rv.data.UUID\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x1d\n\x05\x63olor\x18\x03 \x01(\x0b\x32\x0e.rv.data.Color\x12\x1f\n\x06hotKey\x18\x04 \x01(\x0b\x32\x0f.rv.data.HotKey\x12\x33\n\x1c\x61pplication_group_identifier\x18\x05 \x01(\x0b\x32\r.rv.data.UUID\x12\x1e\n\x16\x61pplication_group_name\x18\x06 \x01(\t\"3\n\x11ProGroupsDocument\x12\x1e\n\x06groups\x18\x01 \x03(\x0b\x32\x0e.rv.data.Groupb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'groups_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GROUP']._serialized_start=58
  _globals['_GROUP']._serialized_end=257
  _globals['_PROGROUPSDOCUMENT']._serialized_start=259
  _globals['_PROGROUPSDOCUMENT']._serialized_end=310
# @@protoc_insertion_point(module_scope)
